// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqAfeS71Ww2QX63MOFQ4tJOiwVqZwa_U',
    appId: '1:1063364342201:android:5cd5c888ae7bd49cd04668',
    messagingSenderId: '1063364342201',
    projectId: 'notes-d2dd9',
    storageBucket: 'notes-d2dd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS7oR-rbfvdRQ3TCWTlbCZF-3TgitBCjQ',
    appId: '1:1063364342201:ios:6f6143d078770c30d04668',
    messagingSenderId: '1063364342201',
    projectId: 'notes-d2dd9',
    storageBucket: 'notes-d2dd9.appspot.com',
    iosClientId: '1063364342201-lsdeepbarcvsik8qitnlga122cat0qlq.apps.googleusercontent.com',
    iosBundleId: 'com.sachin.notes',
  );
}
